api_platform:
    defaults:
        pagination_items_per_page: 10

    oauth:
        # To enable or disable OAuth.
        enabled: true

        # The OAuth client ID.
        clientId: '7f7bce182f8272d42cfc9744d32650dc'

        # The OAuth client secret.
        clientSecret: 'bc8692cfa095e0f308882430f77cb4013ab11ebd82687c78cfba816b102b98eb801be11a06a4afdc278b6b8d64e0340c965726072c074900504dafed09a93ed1'

        # The OAuth type.
        type: 'oauth2'

        # The OAuth flow grant type.
        flow: 'password'

        # The OAuth token url.
        tokenUrl: '/token'

        # The OAuth authentication url.
        authorizationUrl: '/oauth/v2/auth'

        # The OAuth scopes.
        scopes: []

